### ISSUE TITLE
Decompressing some UnityFS archives to memory fails with various exceptions

### ISSUE THREAD

**Issue by kg** [nesrak1/AssetsTools.NET#18]
Hi,

I'm trying to decompress some UnityFS archives that neither UABE or AssetsTools.NET can handle, but AssetsTools is at least providing meaningful exceptions. I'm curious whether it is known that this version of the format doesn't work, or these perhaps are using some new or unusual version of the format?

The header looks like this:
```UnityFS.....5.x.x.2018.4.23f1```

The '5.x.x' makes it unclear to me whether this version of Unity is producing one of the formats your README says are unsupported (5.0-5.4) or what. 2018.4.23f1 appears to be after the officially numbered 5.x releases, but isn't that new... both UABE and AssetTools agree that they are compressed. If it means anything in this context, the FS files are from an Android game. It has MP4 files and CRIWare archives next to it that both decompress as-is with existing tools, there's no weird encryption applied to them, so I would be surprised if they did anything fancy to the UnityFS packages that leaves the headers intact. The 'opening bundle file' window says these archives are compressed with LZ4.

Sample exception messages:
```
An error occurred:
The output char buffer is too small to contain the decoded characters, encoding 'Unicode (UTF-8)' fallback 'System.Text.DecoderReplacementFallback'.

Parameter name: chars
```

```
An error occurred:
Unable to read beyond the end of the stream.
```

```
No valid assets files found in the bundle.
```

```
An error occurred:
Arithmetic operation resulted in an overflow.
```

**Comment by nesrak1** [comment]
> The '5.x.x' makes it unclear to me whether this version of Unity is producing one of the formats your README says are unsupported (5.0-5.4) or what.
That is a normal header, 5.x.x is [always in bundle file headers](https://github.com/nesrak1/AssetsTools.NET/blob/e28f516586778ff4489d0a753e61f014cf50e3d2/AssetTools.NET/Standard/AssetsBundleFileFormat/AssetsBundleHeader06.cs#L9).

As for the exceptions, are these all happening before you open any asset in the file, or only after you open one (besides the one that says no valid assets files).

**Comment by kg** [comment]
They're when I click 'decompress to memory', and there's no stacktrace. Should I attach a debugger to the app before decompressing?

**Comment by nesrak1** [comment]
[AssetsToolsNET_AssetsView.zip](https://github.com/nesrak1/AssetsTools.NET/files/5045482/AssetsToolsNET_AssetsView.zip)
I just changed it to show the whole exception when decompressing a bundle.

**Comment by kg** [comment]
```
An error occurred:
System.ArgumentException: The output char buffer is too small to contain the decoded characters, encoding 'Unicode (UTF-8)' fallback 'System.Text.DecoderReplacementFallback'.

Parameter name: chars

   at System.Text.Encoding.ThrowCharsOverflow()

   at System.Text.Encoding.ThrowCharsOverflow(DecoderNLS decoder, Boolean nothingDecoded)

   at System.Text.UTF8Encoding.GetChars(Byte* bytes, Int32 byteCount, Char* chars, Int32 charCount, DecoderNLS baseDecoder)

   at System.Text.DecoderNLS.GetChars(Byte* bytes, Int32 byteCount, Char* chars, Int32 charCount, Boolean flush)

   at System.Text.DecoderNLS.GetChars(Byte[] bytes, Int32 byteIndex, Int32 byteCount, Char[] chars, Int32 charIndex, Boolean flush)

   at System.Text.DecoderNLS.GetChars(Byte[] bytes, Int32 byteIndex, Int32 byteCount, Char[] chars, Int32 charIndex)

   at System.IO.BinaryReader.InternalReadOneChar()

   at System.IO.BinaryReader.Read()

   at System.IO.BinaryReader.ReadChar()

   at AssetsTools.NET.AssetsFileReader.ReadNullTerminated()

   at AssetsTools.NET.AssetBundleBlockAndDirectoryList06.Read(Int64 filePos, AssetsFileReader reader)

   at AssetsTools.NET.AssetBundleFile.Unpack(AssetsFileReader reader, AssetsFileWriter writer)

   at AssetsView.Winforms.OpenBundleDialog.<>c__DisplayClass10_0.<DecompressBundle>b__0(Object <p0>, DoWorkEventArgs <p1>)
```

```
An error occurred:
System.IO.EndOfStreamException: Unable to read beyond the end of the stream.

   at System.IO.BinaryReader.FillBuffer(Int32 numBytes)

   at System.IO.BinaryReader.ReadUInt32()

   at AssetsTools.NET.AssetsFileReader.ReadUInt32()

   at AssetsTools.NET.AssetBundleBlockAndDirectoryList06.Read(Int64 filePos, AssetsFileReader reader)

   at AssetsTools.NET.AssetBundleFile.Unpack(AssetsFileReader reader, AssetsFileWriter writer)

   at AssetsView.Winforms.OpenBundleDialog.<>c__DisplayClass10_0.<DecompressBundle>b__0(Object <p0>, DoWorkEventArgs <p1>)
```

**Comment by nesrak1** [comment]
Looks like the bundle file table is not being read correctly. I can't really do much without more information/inspecting the file but I can work through debugging it with you if you don't want to send the file.

**Comment by kg** [comment]
Here's three of them, I think each one has a different exception https://www.dropbox.com/s/qmxhjgaqqhagpdp/matrix.zip?dl=1

**Comment by nesrak1** [comment]
Doesn't seem to be a standard bundle format. It has 0x0200 flag set and a compressed table right before the bundle data, but even if I removed the table (from compressed or decompressed bytes), it still wouldn't correctly decompress.

**Comment by kg** [comment]
Makes sense, must be some customized version of it. Thanks for taking a look.
