### ISSUE TITLE
System.IO.EndOfStreamException with AssetViewer

### ISSUE THREAD

**Issue by spacehamster** [nesrak1/AssetsTools.NET#19]
When trying to read PlayerSettings in globalgamemanagers, an EndOfStreamException gets thrown

File: [globalgamemanagers.zip](https://github.com/nesrak1/AssetsTools.NET/files/5127923/globalgamemanagers.zip)

Exception:

![image](https://user-images.githubusercontent.com/3821056/91267432-b4b44a80-e7b6-11ea-97a9-355f7c3801bd.png)

```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.IO.EndOfStreamException: Unable to read beyond the end of the stream.
   at System.IO.BinaryReader.ReadByte()
   at AssetsTools.NET.AssetTypeTemplateField.ReadType(AssetsFileReader reader, UInt64 filePos, AssetTypeValueField valueField, Boolean bigEndian)
   at AssetsTools.NET.AssetTypeTemplateField.ReadType(AssetsFileReader reader, UInt64 filePos, AssetTypeValueField valueField, Boolean bigEndian)
   at AssetsTools.NET.AssetTypeInstance..ctor(UInt32 baseFieldCount, AssetTypeTemplateField[] ppBaseFields, AssetsFileReader reader, Boolean bigEndian, UInt64 filePos)
   at AssetsTools.NET.Extra.AssetsManager.GetATI(AssetsFile file, AssetFileInfoEx info, Boolean fromTypeTree)
   at AssetsView.Winforms.StartScreen.assetList_CellDoubleClick(Object sender, DataGridViewCellEventArgs e)
   at System.Windows.Forms.DataGridView.OnCellDoubleClick(DataGridViewCellEventArgs e)
   at System.Windows.Forms.DataGridView.OnDoubleClick(EventArgs e)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.DataGridView.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4069.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
AssetsView
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/AssetsToolsNET_AssetsView/AssetsView.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4042.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4001.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
AssetsTools.NET
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/AssetsToolsNET_AssetsView/AssetsTools.NET.DLL
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4110.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.
```

**Comment by nesrak1** [comment]
You can tell this is a UABE cldb problem because UABE can't open it either.
![AssetBundleExtractor_apE7HuNZVn](https://user-images.githubusercontent.com/12544505/91335896-a9e9bd80-e796-11ea-9e1b-6592d6b42ce0.png)
Why this problem exists, I'm not sure, but apparently the place where the cldbs come from doesn't always exactly match up with what the assets files actually have in them. It could be a bad cldb version, but I tried with 2018.3 and had the same issue.
![AssetsView_AErlOnViOw](https://user-images.githubusercontent.com/12544505/91340469-b45b8580-e79d-11ea-898e-b17e0b1261c7.png)
^ I was eventually able to load the assets file with some changes to the cldb. I can send that file later if you'd like.

**Comment by spacehamster** [comment]
> ^ I was eventually able to load the assets file with some changes to the cldb. I can send that file later if you'd like.
I would very much appreciate it if you could. Do you know how the cldb is generated in the first place?

**Comment by nesrak1** [comment]
DerPopo said they are made from the player exe (and maybe pdb) files using an unreleased tool he made (I do have a tool that should do the same thing though). They are extracted from the type tree functions (I believe because it's easier than the plain serialization) but sometimes they are slightly different for whatever reason. In this case, I just manually edited the cldb in the class database editor in uabe by just guessing what fields were added/removed.

**Comment by nesrak1** [comment]
Try replacing the classdata.tpk with this. (Or use classdata-uabe.tpk for uabe)
[classdata-U2018.4.10f1.zip](https://github.com/nesrak1/AssetsTools.NET/files/5139548/classdata-U2018.4.10f1.zip)

**Comment by nesrak1** [comment]
Ignore the older messages. Replace the classdata.tpk with this. This should be more accurate.
[classdata-U2018.4.10f1.zip](https://github.com/nesrak1/AssetsTools.NET/files/5139741/classdata-U2018.4.10f1.zip)

**Comment by nesrak1** [comment]
I'm closing this since it's not really a problem with this library but with the cldbs. Feel free to reopen if you still have issues/questions.
