### ISSUE TITLE
Adding a value to an array in an asset

### ISSUE THREAD

**Issue by Raicuparta** [nesrak1/AssetsTools.NET#20]
`enabledVRDevices` has an array inside it, so I can get that array like so:

```cs
var enabledVRDevices = baseField.Get("enabledVRDevices").Get(0);
```

If I want to change the value of the first element of the array, I do this:

```cs
enabledVRDevices .Get(0).SetValue("Something");
```

This works as expected, and when I write the changes to a file I can confirm that the new value is there.

But what I need is to actually add a new value to the array, since it starts out as empty.

I tried with `SetChildrenList` but in the final file the array is always empty:

```cs
var something = new AssetTypeValueField();
something .value = new AssetTypeValue(EnumValueTypes.ValueType_String, "Something");
enabledVRDevices .SetChildrenList(new[] { something });
```

I was trying to find some way to just to something like this:

```cs
var newArray = new AssetTypeArray();
enabledVRDevices.GetValue().Set(newArray);
```
But I have no idea how to add anything inside this `newArray`. Seems like that part is commented out in the source code?

So, what is the correct way to add items into an array here?

**Comment by nesrak1** [comment]
Yeah, adding items to an array is something I want to make a lot easier. Maybe the original library has some other function that I'm not aware of that does something like this (AddChildren maybe? no idea how it works.) Here's some code which should add one item into the array:
```cs
static void Main(string[] args)
{
    AssetsManager am = new AssetsManager();
    am.LoadClassPackage("classdata.tpk");
    AssetsFileInstance ggm = am.LoadAssetsFile("globalgamemanagers", false);
    AssetsFile ggmFile = ggm.file;
    AssetsFileTable ggmTable = ggm.table;
    am.LoadClassDatabaseFromPackage(ggmFile.typeTree.unityVersion);
	
    List<AssetsReplacer> replacers = new List<AssetsReplacer>();
	
    AssetFileInfoEx buildSettings = ggmTable.GetAssetInfo(11);
    AssetTypeValueField buildSettingsBase = am.GetATI(ggmFile, buildSettings).GetBaseField();
    AssetTypeValueField enabledVRDevices = buildSettingsBase.Get("enabledVRDevices").Get("Array");
    AssetTypeTemplateField stringTemplate = enabledVRDevices.templateField.children[1];
    AssetTypeValueField[] vrDevicesList = new AssetTypeValueField[]
    {
        StringField("OculusDrift", stringTemplate)
    };
    enabledVRDevices.SetChildrenList(vrDevicesList);
	
    replacers.Add(new AssetsReplacerFromMemory(0, buildSettings.index, (int)buildSettings.curFileType, 0xffff, buildSettingsBase.WriteToByteArray()));
	
    using (AssetsFileWriter writer = new AssetsFileWriter(File.OpenWrite("globalgamemanagers-new")))
    {
        ggmFile.Write(writer, 0, replacers, 0);
    }
}
static AssetTypeValueField StringField(string str, AssetTypeTemplateField template)
{
    return new AssetTypeValueField()
    {
        children = null, childrenCount = 0,
        templateField = template,
        value = new AssetTypeValue(EnumValueTypes.ValueType_String, str)
    };
}
```
That should work for now, but there should probably be like a `CreateStringValue("some string")` so you don't have to write all this extra code trying to create an AssetTypeValueField.

I also updated the repo code to correctly write asset length, so make sure to update your lib.
[AssetsTools.NET.dll.zip](https://github.com/nesrak1/AssetsTools.NET/files/5226758/AssetsTools.NET.dll.zip)

**Comment by Raicuparta** [comment]
Awesome, this works! This template stuff still confuses me a bit 😛 I will close this since it's resolved, thank you so much!

**Comment by Raicuparta** [comment]
If you don't feel like implementing an easier way to add items to arrays, might be a good idea to include a snippet like that in the Readme? Since it's so different than setting a single value.

**Comment by nesrak1** [comment]
What about something like this? I know it's a little awkward setting the actual value after creating a ValueField, but because it does deep copy, setting only the top level value might be a little weird so I just didn't add it.

```cs
...
AssetFileInfoEx buildSettings = ggmTable.GetAssetInfo(11);
AssetTypeValueField buildSettingsBase = am.GetATI(ggmFile, buildSettings).GetBaseField();
AssetTypeValueField enabledVRDevices = buildSettingsBase.Get("enabledVRDevices").Get("Array");

AssetTypeValueField arrayItem = AssetTypeValueBuilder.DefaultValueFieldFromArrayTemplate(enabledVRDevices);
arrayItem.GetValue().Set("OculusDrift");
AssetTypeValueField[] vrDevicesList = new AssetTypeValueField[]
{
    arrayItem
};
enabledVRDevices.SetChildrenList(vrDevicesList);
...
```

**Comment by Raicuparta** [comment]
Yeah that seems slightly better, especially since it removes the need for a comment explaining that `[1]` from before. BTW this is what I used it for (work in progress): https://github.com/Raicuparta/UnityVRPatcher

**Comment by mineblock11** [comment]
Hey, im doing something similar, but I am clearning the "enabledVrDevices" array - when loading the base an error occurs;

```
System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=AssetsTools.NET
  StackTrace:
   at AssetsTools.NET.Extra.AssetHelper.FindAssetClassByID(ClassDatabaseFile cldb, UInt32 id)
   at AssetsTools.NET.Extra.AssetsManager.GetTemplateBaseField(AssetsFile file, AssetFileInfoEx info, Boolean forceFromCldb)
   at AssetsTools.NET.Extra.AssetsManager.GetATI(AssetsFile file, AssetFileInfoEx info, Boolean forceFromCldb)
   at PrePatcher.MainWindow.VB$StateMachine_2_HandleFileOpen.MoveNext() in D:\VB\PrePatcher\MainWindow.xaml.vb:line 53

  This exception was originally thrown at this call stack:
    [External Code]
    PrePatcher.MainWindow.HandleFileOpen(String) in MainWindow.xaml.vb
```

My code:

```vb
Log("Patched boot.config")

        Dim am = New AssetsManager()

        Dim globalGameManagersPath = Path.Combine("./" & filename_noext, "assets", "bin", "Data", "globalgamemanagers")

        Log("Loading globalgamemanagers")

        Dim globalGameManagers = am.LoadAssetsFile(globalGameManagersPath, False)
        Dim buildSettingsInst = globalGameManagers.table.GetAssetsOfType(AssetClassID.BuildSettings).First()

        Log("Replacing enabledVrDevices with empty vector")
        Dim buildSettings = globalGameManagers.table.GetAssetInfo(11)
        Dim buildSettingsBase = am.GetATI(globalGameManagers.file, buildSettings).GetBaseField()
        Dim enabledVRDevices = buildSettingsBase.Get("enabledVRDevices").Get("Array")
        Dim vrDevicesList() As AssetTypeValueField = {}
        enabledVRDevices.SetChildrenList(vrDevicesList)

        Dim repl = New AssetsReplacerFromMemory(0, buildSettingsInst.index, buildSettingsInst.curFileType, &HFFFF, buildSettingsBase.WriteToByteArray())

        Dim stream = File.OpenWrite("resources-modified.assets")
        Dim writer = New AssetsFileWriter(stream)
        Dim lAR = New List(Of AssetsReplacer)()
        lAR.Add(repl)
        globalGameManagers.file.Write(writer, 0, lAR, 0)
        writer.Close()
        stream.Close()
```

**Comment by mineblock11** [comment]
Is there anything im doing wrong?
