### ISSUE TITLE
UnityFS 2019.4.5f1 crashes - System.OverflowException

### ISSUE THREAD

**Issue by BlazingTwist** [nesrak1/AssetsTools.NET#26]
This seems to hold true for any 2019.4.5f1 bundle that I throw at it, the 2019.1.8f1 counterparts work fine.
Here's the Stacktrace:
```
System.OverflowException: Arithmetic operation resulted in an overflow.
   at AssetsTools.NET.Type_0D.Read(Boolean hasTypeTree, AssetsFileReader reader, UInt32 version)
   at AssetsTools.NET.TypeTree.Read(AssetsFileReader reader, UInt32 version)
   at AssetsTools.NET.AssetsFile..ctor(AssetsFileReader reader)
   at AssetsTools.NET.Extra.AssetsFileInstance..ctor(Stream stream, String filePath, String root)
   at AssetsTools.NET.Extra.AssetsManager.LoadAssetsFile(Stream stream, String path, Boolean loadDeps, String root)
   at AssetsView.Winforms.StartScreen.LoadBundleFile(String path)
   at AssetsView.Winforms.StartScreen.addFileToolStripMenuItem_Click(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

This happens both when opening the bundle using AssetsView and my own implementation (which calls the AssetsFileInstance constructor)

I tried loading the bundle using several applications
* UABE says they're not valid Assets files.
* AssetStudio doesn't load them at all, no warnings / errors

On the other hand
* uTinyRipper seems to unpack without trouble
* devXUnityUnpacker loads the bundles fine as well

I did see you mentioning reading the assets manually using the `AssetsFileReader` on the main ReadMe, could you elaborate on that?

**Comment by nesrak1** [comment]
Looks like a type tree read bug. Was testing on addressables from 2019.4 but those don't have typetrees so it's possible I missed something. Will try to make a build and see if I can debug.

**Comment by nesrak1** [comment]
I just tested two different versions of 2019.4 for bundles and both loaded in both AssetsView and AssetStudio (I already know UABE is broken for newer bundles so this isn't a surprise). I also checked the code in uTinyRipper and it looks to be the same as what I am doing right now, so I'm surprised it wouldn't work. If you can send a file to test with that would make it easy, but if you can't I can try to find another way to help debug.

**Comment by BlazingTwist** [comment]
Sure can do.
[example_2019.4.5f1.zip](https://github.com/nesrak1/AssetsTools.NET/files/5691683/example_2019.4.5f1.zip)

In case comparing them to the old versions might help you. (I don't see any difference between the old and new headers, but something clearly must be different)
[example_2019.1.8f1.zip](https://github.com/nesrak1/AssetsTools.NET/files/5691680/example_2019.1.8f1.zip)

**Comment by nesrak1** [comment]
AssetsView is opening the new bundles fine for me. (Make sure you got the prerelease instead of the old version 3?)

**Comment by BlazingTwist** [comment]
I feel a little stupid now. That did it.
As Github is only showing non-prerelease versions I assumed Update 3 was the latest release.
Sorry about that.
