### ISSUE TITLE
Issue Creating a GameObject Asset

### ISSUE THREAD

**Issue by DigWorm0** [nesrak1/AssetsTools.NET#27]
I am trying to create a GameObject asset using the following code:
```C#
// Import
AssetsManager assetsManager = new AssetsManager();
List<AssetsReplacer> replacers = new List<AssetsReplacer>();
assetsManager.LoadClassPackage("classdata.tpk");
AssetsFileInstance assetsFileInstance = assetsManager.LoadAssetsFile("sharedassets0.assets", false);
assetsManager.LoadClassDatabaseFromPackage(assetsFileInstance.file.typeTree.unityVersion);
AssetsFileTable assetsFileTable = assetsFileInstance.table;

// Template
AssetTypeTemplateField templateField = new AssetTypeTemplateField();
ClassDatabaseType cldbType = AssetHelper.FindAssetClassByName(assetsManager.classFile, "GameObject");
templateField.FromClassDatabase(assetsManager.classFile, cldbType, 0);

// New Asset
AssetTypeValueField newAsset = ValueBuilder.DefaultValueFieldFromTemplate(templateField);
replacers.Add(new AssetsReplacerFromMemory(0, assetsFileTable.assetFileInfo.Max(i => i.index) + 1, cldbType.classId, 0xFFFF, newAsset.WriteToByteArray()));

// Export
AssetsFileWriter writer = new AssetsFileWriter(File.OpenWrite("sharedassets0-new.assets"));
assetsFileInstance.file.Write(writer, 0, replacers, 0);
writer.Close();
```
The code runs without any error. However, when I try to view the GameObject using AssetsView, I get the following error:
```
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at AssetsTools.NET.AssetTypeValueField.get_Item(Int32 index)
   at AssetsView.Winforms.GameObjectViewer.GetRootGameObject(AssetExternal ext)
   at AssetsView.Winforms.GameObjectViewer.GameObjectViewer_Load(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```
I think this is an issue with my code and not AssetsView. How should I correctly initialize a new GameObject asset?

Note: 
I am using the AssetsTools.NET.dll provided in AssetsTools.NET.zip in #22. The rest of the files are from update 14 (2.0.6)

**Comment by nesrak1** [comment]
Most likely it's because you didn't add a transform to the GameObject (which unity usually requires on all GameObjects) and AssetsView is just assuming it always exists.

Also thanks for reminding me about the release, I will make a new one with that bug fix now.

**Comment by nesrak1** [comment]
```cs
// Import
AssetsManager assetsManager = new AssetsManager();
List<AssetsReplacer> replacers = new List<AssetsReplacer>();
assetsManager.LoadClassPackage("classdata.tpk");
AssetsFileInstance assetsFileInstance = assetsManager.LoadAssetsFile("sharedassets0.assets", false);
assetsManager.LoadClassDatabaseFromPackage(assetsFileInstance.file.typeTree.unityVersion);
AssetsFileTable assetsFileTable = assetsFileInstance.table;

// Template
AssetTypeTemplateField gameObjectTemplate = new AssetTypeTemplateField();
ClassDatabaseType cldbGameObject = AssetHelper.FindAssetClassByName(assetsManager.classFile, "GameObject");
gameObjectTemplate.FromClassDatabase(assetsManager.classFile, cldbGameObject, 0);

AssetTypeTemplateField transformTemplate = new AssetTypeTemplateField();
ClassDatabaseType cldbTransform = AssetHelper.FindAssetClassByName(assetsManager.classFile, "Transform");
transformTemplate.FromClassDatabase(assetsManager.classFile, cldbTransform, 0);

// New Asset
long largestId = assetsFileTable.assetFileInfo.Max(i => i.index);
long transformId = largestId + 1;
long gameObjectId = largestId + 2;

// Transform
AssetTypeValueField newTransform = ValueBuilder.DefaultValueFieldFromTemplate(transformTemplate);

//set transform parent to what will be our new gameobject
AssetTypeValueField m_GameObject = newTransform.Get("m_GameObject");
m_GameObject.Get("m_FileID").GetValue().Set(0); //should default to 0 so this is kind of redundant
m_GameObject.Get("m_PathID").GetValue().Set(gameObjectId);

replacers.Add(new AssetsReplacerFromMemory(0, transformId, cldbTransform.classId, 0xFFFF, newTransform.WriteToByteArray()));

// GameObject
AssetTypeValueField newGameObject = ValueBuilder.DefaultValueFieldFromTemplate(gameObjectTemplate);

//set name
newGameObject.Get("m_Name").GetValue().Set("Some Gameobject");

//set component array
AssetTypeValueField m_Component = newGameObject.Get("m_Component").Get("Array");
//first we create a reference to the transform and set the values
AssetTypeValueField transformRef = ValueBuilder.DefaultValueFieldFromArrayTemplate(m_Component.GetTemplateField()).Get("component");
transformRef.Get("m_FileID").GetValue().Set(0); //should default to 0 so this is kind of redundant
transformRef.Get("m_PathID").GetValue().Set(transformId);
//now create an array out of our one reference to the transform
m_Component.GetValue().Set(new AssetTypeArray());
m_Component.SetChildrenList(new[] { transformRef });

replacers.Add(new AssetsReplacerFromMemory(0, gameObjectId, cldbGameObject.classId, 0xFFFF, newGameObject.WriteToByteArray()));

// Export
AssetsFileWriter writer = new AssetsFileWriter(File.OpenWrite("sharedassets0-new.assets"));
assetsFileInstance.file.Write(writer, 0, replacers, 0);
writer.Close();
```

Here is some example code to do that

**Comment by DigWorm0** [comment]
It works, thank you very much!
