### ISSUE TITLE
AssetsView Update 20 (2.0.11) closing instantly

### ISSUE THREAD

**Issue by SFGrenade** [nesrak1/AssetsTools.NET#68]
[The currently latest version of AssetsView](https://github.com/nesrak1/AssetsTools.NET/releases/latest) just closes itself after i start it, not even showing the window and i have no idea what went wrong.

OS: Windows 10 21H2

**Comment by SFGrenade** [comment]
crash log:
```
Application: AssetsView.exe
CoreCLR Version: 4.700.20.36602
.NET Core Version: 3.1.7
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.FileLoadException: Could not load file or assembly 'System.Drawing.Common, Version=4.0.2.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The located assembly's manifest definition does not match the assembly reference. (0x80131040)
File name: 'System.Drawing.Common, Version=4.0.2.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
   at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, StackCrawlMarkHandle stackMark, ObjectHandleOnStack assemblyLoadContext, Boolean loadTypeFromPartialName, ObjectHandleOnStack type, ObjectHandleOnStack keepalive)
   at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, StackCrawlMark& stackMark, AssemblyLoadContext assemblyLoadContext, Boolean loadTypeFromPartialName)
   at System.RuntimeType.GetType(String typeName, Boolean throwOnError, Boolean ignoreCase, StackCrawlMark& stackMark)
   at System.Type.GetType(String typeName, Boolean throwOnError)
   at System.Resources.Extensions.DeserializingResourceReader.FindType(Int32 typeIndex)
   at System.Resources.Extensions.DeserializingResourceReader.DeserializeObject(Int32 typeIndex)
   at System.Resources.Extensions.DeserializingResourceReader._LoadObjectV2(Int32 pos, ResourceTypeCode& typeCode)
   at System.Resources.Extensions.DeserializingResourceReader.LoadObjectV2(Int32 pos, ResourceTypeCode& typeCode)
   at System.Resources.Extensions.DeserializingResourceReader.LoadObject(Int32 pos, ResourceTypeCode& typeCode)
   at System.Resources.Extensions.RuntimeResourceSet.GetObject(String key, Boolean ignoreCase, Boolean isString)
   at System.Resources.Extensions.RuntimeResourceSet.GetObject(String key, Boolean ignoreCase)
   at System.Resources.ResourceManager.GetObject(String name, CultureInfo culture, Boolean wrapUnmanagedMemStream)
   at System.Resources.ResourceManager.GetObject(String name)
   at AssetsView.Winforms.StartScreen.InitializeComponent() in C:\Users\nesquack\Documents\GitReposLocal\AssetsTools.NET\AssetsView\Winforms\StartScreen.Designer.cs:line 415
   at AssetsView.Winforms.StartScreen..ctor() in C:\Users\nesquack\Documents\GitReposLocal\AssetsTools.NET\AssetsView\Winforms\StartScreen.cs:line 34
   at AssetsView.Program.Main() in C:\Users\nesquack\Documents\GitReposLocal\AssetsTools.NET\AssetsView\Program.cs:line 20
```

**Comment by nesrak1** [comment]
[AssetsToolsNET_AssetsView_nc31_with_drawing.zip](https://github.com/nesrak1/AssetsTools.NET/files/8092675/AssetsToolsNET_AssetsView_nc31_with_drawing.zip)
Fixed by adding System.Drawing nuget package.
